version: 2
registries:
  sap-artifactory:
    type: python-index
    url: https://common.repositories.cloud.sap/artifactory/api/pypi/build.releases.pypi/
    username: ${{secrets.ARTIFACTORY_USERNAME}}
    password: ${{secrets.ARTIFACTORY_TOKEN}}
    replaces-base: true
updates:
  - package-ecosystem: uv
    target-branch: 'main'
    directory: /
    registries:
      - sap-artifactory
    schedule:
      interval: daily
      time: '22:00'
    cooldown:
      default-days: 5
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: github-actions
    target-branch: 'main'
    directory: /
    schedule:
      interval: daily
      time: '22:00'
    cooldown:
      default-days: 5
    commit-message:
      prefix: 'chore(deps)'
