[project]
name = "ai-sdk-python"
version = "0.0.0"
requires-python = ">=3.10"

[[tool.uv.index]]
name = "artifactory"
url = "https://common.repositories.cloud.sap/artifactory/api/pypi/build.releases.pypi/simple/"
default = true

[tool.uv.sources]
sap-ai-sdk-base = { workspace = true }
sap-ai-sdk-core = { workspace = true }
sap-ai-sdk-gen = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.pytest]
markers = [
    "bedrock: mark a test as a bedrock test running in a different environment",
]
