sonar.projectKey=generative-ai-hub-sdk
sonar.projectName=generative-ai-hub-sdk
sonar.projectVersion=6.8.0
sonar.python.version=3.10
sonar.sources=./gen_ai_hub
sonar.exclusions=scripts/**,tests/**,tests/**,integration_tests/**,integration_tests/**
sonar.cpd.exclusions=gen_ai_hub/proxy/native/openai/clients.py,**/orchestration_v2/sse_client.py,**/orchestration_v2/service.py,**/orchestration_v2/models/tools.py,**/orchestration_v2/models/data_masking.py,**/orchestration_v2/models/multimodal_items.py,**/orchestration_v2/__init__.py,**/**/orchestration_v2/models/__init__.py, **/**/document_grounding/__init__.py, **/**/document_grounding/models/__init__.py
sonar.dynamicAnalysis=reuseReports
sonar.core.codeCoveragePlugin=cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=unit_tests.xml
sonar.python.pylint.reportPath=pylint.log
sonar.qualitygate.wait=true

# project metadata
sonar.links.homepage=https://www.sap.com
sonar.links.ci=https://jenkins.ml.only.sap/job/AI-Foundation/job/generative-ai-hub-sdk/
sonar.pullrequest.github.repository=AI/generative-ai-hub-sdk
sonar.links.issue=https://sapjira.wdf.sap.corp/projects/AIWDF
sonar.links.scm=https://github.wdf.sap.corp/AI/generative-ai-hub-sdk
