{{- /*
Since a separate WorkflowTemplate is required for each worker cluster, we recreate the tenantTests dict, remove the "worker" key and add keys for each worker cluster.
Also add other required vars (ex- customTenantName) to the tenantTests dict
*/}}
{{- $tenantTests := .Values.tenantTests -}}
{{- $mainCustomTestTenantEnabled := tpl $tenantTests.main.customTestTenantEnabled $ }}
{{- if and (hasKey $tenantTests "main") (eq $mainCustomTestTenantEnabled "true") }}
  {{- range $_, $mainTestTenant := $.Values.customTestTenants.main }}
    {{- if eq $mainTestTenant.key "sap-internal"}}
      {{ $_ := set $tenantTests.main "customTenantName" $mainTestTenant.name }}
      {{ $_ := set $tenantTests.main "customTestTenantEnabled" $mainCustomTestTenantEnabled }}
    {{- end }}
  {{- end }}
{{- end }}

{{- if hasKey $tenantTests "worker" }}
  {{- $worker_enabled := tpl $tenantTests.worker.enabled $ }}
  {{- $worker_secret := tpl $tenantTests.worker.secret $ }}
  {{- $workerCustomTestTenantEnabled := tpl $tenantTests.worker.customTestTenantEnabled $ }}
  {{- if eq $worker_enabled "true" }}
    {{ $_ := unset $tenantTests "worker" }}
    {{- range $_, $w := $.Values.clusters }}
      {{- if not (eq $w.name "main") }}
        {{- $standardWorkerTestTenant := ""}}
        {{- $workerTestTenants := index $.Values.customTestTenants $w.gardenerName }}
        {{- range $_, $workerTestTenant := $workerTestTenants}}
          {{- if eq $workerTestTenant.key "sap-internal"}}
            {{- $standardWorkerTestTenant = $workerTestTenant.name}}
          {{- end }}
        {{- end }}
        {{ $worker := dict "enabled" $worker_enabled "secret" $worker_secret "customTestTenantEnabled" $workerCustomTestTenantEnabled "customTenantName" $standardWorkerTestTenant }}
        {{ $_ := set $tenantTests $w.gardenerName $worker }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: >-
      this workflow runs the ai-core-sdk acceptance test.
    workflows.argoproj.io/maintainer: '@mlf-gitops'
    workflows.argoproj.io/tags: result-evaluation
    workflows.argoproj.io/version: '>= 2.9.0'
    workflows.argoproj.io/container-runtime-executor: emissary
  namespace: {{ .Release.Namespace }}
  name: at-ai-core-sdk
spec:
  templates:
  - name: acceptance-tests
    inputs:
      parameters:
      - name: workdir
      - name: test-type
      - name: workflow-sa
      - name: debug
      - name: component-timeout-seconds
    steps:
      -
{{- range $tenantCluster, $tenantClusterTestConfig := $tenantTests -}}
{{- $enabled := tpl $tenantClusterTestConfig.enabled $ }}
{{- if and (eq $enabled "true") (not (has $tenantCluster $.Values.testsuite.exclude)) }}
        - name: acceptance-tests-{{ $tenantCluster }}
          templateRef:
            name: at-ai-core-sdk-{{ $tenantCluster }}
            template: acceptance-tests
          arguments:
            parameters:
            - {name: workdir, value: '/workdir'}
            - {name: test-type, value: {{ `"{{inputs.parameters.test-type}}"` }} }
            - {name: cluster-name-short, value: {{ $tenantCluster }} }
            - {name: workflow-sa, value: {{ `"{{workflow.parameters.workflow-sa}}"` }} }
            - {name: debug, value: {{ `"{{inputs.parameters.debug}}"` }} }
            - {name: component-timeout-seconds, value: {{ `"{{inputs.parameters.component-timeout-seconds}}"` }} }
{{- end }}
{{- end }}


{{- range $tenantCluster, $tenantClusterTestConfig := $tenantTests -}}
{{- $enabled := tpl $tenantClusterTestConfig.enabled $ }}
{{- if eq $enabled "true" }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: >-
      this workflow runs the ai-core-sdk acceptance test.
    workflows.argoproj.io/maintainer: '@mlf-gitops'
    workflows.argoproj.io/tags: result-evaluation
    workflows.argoproj.io/version: '>= 2.9.0'
    workflows.argoproj.io/container-runtime-executor: emissary
  namespace: {{ $.Release.Namespace }}
  name: at-ai-core-sdk-{{ $tenantCluster }}
spec:
  templates:
  - name: acceptance-tests
    activeDeadlineSeconds: {{ `"{{inputs.parameters.component-timeout-seconds}}"` }}
    serviceAccountName: {{ `"{{inputs.parameters.workflow-sa}}"` }}
    inputs:
      parameters:
      - name: workdir
      - name: cluster-name-short
      - name: test-type
      - name: workflow-sa
      - name: debug
      - name: component-timeout-seconds
    container:
      image: {{ printf "%s/%s:%s" $.Values.imageRepository $.Values.image $.Chart.Version }}
      command: [python3, -c]
      volumeMounts:
      - {name: workspace, mountPath: {{ `"{{inputs.parameters.workdir}}"` }} }
      command:
        - python3
        - '-c'
      args:
       - |
        import os, uuid
        import requests
        from requests.auth import HTTPBasicAuth
        import time
        import json
        import base64

        MAX_RETRIES = 10
        SLEEP_SEC = 20
        TEST_DOCKER_IMAGE_SECRET_NAME = "tests-docker-image-secret"

        auth_url = os.environ.get('XSUAA_ENDPOINT') + '/oauth/token?grant_type=client_credentials'
        api_url = os.environ.get('DEPLOYMENT_ENDPOINT')
        host = os.environ.get('DOCKER_REGISTRY_FOR_TESTS_HOST')
        user = os.environ.get('DOCKER_REGISTRY_FOR_TESTS_USER')
        password = os.environ.get('DOCKER_REGISTRY_FOR_TESTS_PASSWORD')

        response = requests.get(auth_url, auth=HTTPBasicAuth(os.environ.get('XSUAA_CLIENT_ID'), os.environ.get('XSUAA_CLIENT_SECRET')))
        token = response.json().get('access_token')

        rg_id = "aicore-sdk" + str(uuid.uuid4())[0:10]

        def _create_resource_group(headers):
            payload = {
                "resourceGroupId": rg_id
            }
            try:
                response = requests.post(api_url + '/v2/admin/resourceGroups', headers=headers, data=json.dumps(payload))
            except Exception as e:
                print(e)

            if response.status_code != 202:
                    raise Exception(f"Could not create the resource group. Status Code : {response.status_code}. Response : {response.text}")

            is_resource_group_provisioned = False
            for i in range(1,11):
                print(f"Attempt ({i}/10) : Checking if Resource Group '{rg_id}' has been provisioned.")
                if _check_resource_group_provisioned(rg_id, headers):
                    is_resource_group_provisioned = True
                    break
                else:
                    print(f"Attempt ({i}/10) : Sleeping for 6 seconds before re-trying...")
                    time.sleep(6)
            if not is_resource_group_provisioned:
                raise Exception("Could not provision resource group '{rg_id}' after 10 retries.")

            resource_group_id = response.json().get('resourceGroupId')
            print(f"Created Resource Group ID : {resource_group_id}")
            return resource_group_id

        def _delete_resource_group(headers):
            try:
                response = requests.delete(api_url + f'/v2/admin/resourceGroups/{rg_id}', headers=headers)
            except Exception as e:
                print(e)

            if response.status_code != 202:
                    raise Exception(f"Could not delete the resource group. Status Code : {response.status_code}. Response : {response.text}")

        def _check_resource_group_provisioned(resource_group_id, headers):
            response = requests.get((api_url + '/v2/admin/resourceGroups/{}').format(resource_group_id), headers=headers)
            if response.status_code == 200 and response.json().get('status') == 'PROVISIONED':
                    return True
            print(f"Resource Group '{resource_group_id}' provision check failed. Response : {response.content}")
            return False

        def _create_secret_for_docker_registry_for_tests(api_url: str, docker_registry_host: str, user: str, password: str,
                                                         resource_group_id: str, headers):
            if not docker_registry_host.startswith("https://"):
                docker_registry_host = "https://" + docker_registry_host

            password = password.replace('"', '\\"').replace("\n", "\\n")

            data = {
              "name": TEST_DOCKER_IMAGE_SECRET_NAME,
              "data": {
                ".dockerconfigjson": json.dumps({
                  "auths": {
                    docker_registry_host: {
                      "auth": base64.b64encode(password.encode("utf-8")).decode("utf-8"),
                    }
                  }
                })
              }
            }

            try:
              response = requests.post(api_url + '/v2/admin/dockerRegistrySecrets', headers=headers, data=json.dumps(data))
            except Exception as e:
                print(e)

            if response.status_code != 202 and response.status_code != 409:
                raise Exception(f"Failed to create secret for docker registry for tests for {resource_group_id}: {response.status_code}, "
                                f"{response.text}")

        headers = {
            'Authorization': 'Bearer '+token,
            'Content-Type': 'application/json'
        }

        # Create the test resource group
        _create_resource_group(headers)

        _create_secret_for_docker_registry_for_tests(api_url=api_url, docker_registry_host=host,user=user,password=password,resource_group_id=rg_id,headers=headers)

        ## Create Configuration

        configuration_payload = {
            "name": "conf_" + str(uuid.uuid4())[0:6],
            "executableId": "ai-core-sdk-test-executable",
            "scenarioId": "aaaaaaaa-9999-8888-7777-uuuuuuuuuuuu",
            "versionId": "0.0.1",
            "parameterBindings": [],
            "inputArtifactBindings": []
        }
        headers["AI-Resource-Group"] = rg_id

        try:
            response = requests.post(api_url + '/v2/lm/configurations', headers=headers, data=json.dumps(configuration_payload))
            configuration_id = response.json().get('id')
        except Exception as e:
            print(e)

        ## Create Execution

        execution_payload = {
            "configurationId": configuration_id
        }

        try:
            response = requests.post(api_url + '/v2/lm/executions', headers=headers, data=json.dumps(execution_payload))
            execution_id = response.json().get('id')
        except Exception as e:
            print(e)


        ## check for completed status

        for i in range(MAX_RETRIES):
            try:
                response = requests.get(api_url + f'/v2/lm/executions/{execution_id}', headers=headers)
                execution_status = response.json().get('status')
                time.sleep(SLEEP_SEC)
                if execution_status=="COMPLETED":
                    print("Execution is Completed!!")
                    break
            except Exception as ex:
                print("Execution is not yet complete")


        # Clean up of resource group
        _delete_resource_group(headers)
      resources:
        limits:
          memory: 1024Mi
          cpu: 500m
        requests:
          memory: 128Mi
          cpu: 100m
      env:
        - name: DEPLOYMENT_ENDPOINT
          value: {{ printf "https://%s.%s" $.Values.unifiedApiSubdomain $.Values.clusterDomain }}
        - name: DOCKER_REGISTRY_FOR_TESTS_HOST
          valueFrom:
            secretKeyRef:
              name: docker-registry-for-tests-read-only
              key: HOST
        - name: DOCKER_REGISTRY_FOR_TESTS_USER
          valueFrom:
            secretKeyRef:
              name: docker-registry-for-tests-read-only
              key: USER
        - name: DOCKER_REGISTRY_FOR_TESTS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: docker-registry-for-tests-read-only
              key: PASSWORD
{{- if eq $tenantClusterTestConfig.customTestTenantEnabled "true" }}
        - name: XSUAA_ENDPOINT
          value: {{ $.Values.testTenantAuthServiceBaseUrl }}
        - name: XSUAA_CLIENT_ID
          value: {{ $tenantClusterTestConfig.customTenantName }}
        - name: XSUAA_CLIENT_SECRET
          value: ""
{{- else }}
        - name: XSUAA_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: {{ $tenantClusterTestConfig.secret }}
              key: url
        - name: XSUAA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ $tenantClusterTestConfig.secret }}
              key: clientid
        - name: XSUAA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ $tenantClusterTestConfig.secret }}
              key: clientsecret
{{- end }}
{{- end }}
{{- end }}
