name: simple
version: 0.0.1
scenario: my-scenario
spec:
  config:
    modules:
      - prompt_templating:
          prompt:
            template:
              - role: user
                content: "First man on the moon, answer in json"
            response_format:
              type: json_object
          model:
            name: gpt-4o
