sonar.projectKey=ai-api-client-sdk
sonar.projectName=ai-api-client-sdk
sonar.projectVersion=3.4.0
sonar.sources=./ai_api_client_sdk
sonar.exclusions=scripts/**,tests/**
sonar.dynamicAnalysis=reuseReports
sonar.core.codeCoveragePlugin=cobertura
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=unit_tests.xml
sonar.python.pylint.reportPath=pylint.log
sonar.qualitygate.wait=true
