import os
from enum import Enum

AI_CORE_PREFIX = 'AICORE'
AUTH_ENDPOINT_SUFFIX = '/oauth/token'
ENV_VAR_AICORE_CONFIG_FILE = f'{AI_CORE_PREFIX}_CONFIG'
DEBUG_ENV_VAR_NAME = "DEBUG"
DEFAULT_HOME_PATH = os.path.join(os.path.expanduser('~'), '.aicore')
ENV_VAR_AICORE_HOME_PATH = f'{AI_CORE_PREFIX}_HOME'
ENV_VAR_AICORE_PROFILE = f'{AI_CORE_PREFIX}_PROFILE'
ENV_VAR_AICORE_SERVICE_KEY = f'{AI_CORE_PREFIX}_SERVICE_KEY'
VCAP_AICORE_SERVICE_NAME = 'aicore'
ENV_VAR_VCAP_SERVICES = 'VCAP_SERVICES'


class Timeouts(Enum):
    READ_TIMEOUT = 60
    CONNECT_TIMEOUT = 60
    NUM_REQUEST_RETRIES = 3
