sonar.projectKey=ai-core-sdk
sonar.projectName=ai-core-sdk
sonar.projectVersion=3.3.0
sonar.sources=./ai_core_sdk
sonar.exclusions=scripts/**,tests/**,integration_tests/**, ai_core_sdk/helpers/constants.py
sonar.dynamicAnalysis=reuseReports
sonar.core.codeCoveragePlugin=cobertura
sonar.python.coverage.reportPaths=**/coverage.xml
sonar.python.xunit.reportPath=**/unit_tests.xml
sonar.python.pylint.reportPath=**/pylint.log
sonar.qualitygate.wait=true
