"""Sample: Document Grounding search using the Kiota-generated client.

The Kiota client uses a request-builder tree. After running `make generate-kiota`,
the generated root client (`DocumentGroundingClient`) exposes path segments as
properties, e.g.:

    client.generated.retrieval.search.post(body)

The request and response models live under:
    gen_ai_hub.document_grounding_generation_kiota.generated.models.*
"""

from gen_ai_hub.document_grounding_generation_kiota import KiotaGroundingApiClient

# These model classes are generated by `make generate-kiota` and will be available
# under gen_ai_hub.document_grounding_generation_kiota.generated.models.*
# Imported lazily here so the module can be imported even before generation is run.


async def retrieval_search():
    from gen_ai_hub.document_grounding_generation_kiota.generated.models.retrieval_search_input import (
        RetrievalSearchInput,
    )
    from gen_ai_hub.document_grounding_generation_kiota.generated.models.retrieval_search_filter import (
        RetrievalSearchFilter,
    )
    from gen_ai_hub.document_grounding_generation_kiota.generated.models.retrieval_search_configuration import (
        RetrievalSearchConfiguration,
    )

    client = KiotaGroundingApiClient()

    body = RetrievalSearchInput()
    body.query = "Features of Generative AI Hub"

    search_filter = RetrievalSearchFilter()
    search_filter.id = "SAPHelp"
    search_filter.data_repository_type = "help.sap.com"

    search_config = RetrievalSearchConfiguration()
    search_config.max_chunk_count = 5
    search_filter.search_configuration = search_config

    body.filters = [search_filter]

    result = await client.generated.retrieval.search.post(body)
    return {"result": result}
