project:
  executeType: 'pythonLib'
  unitTestsFolder: 'tests'
  deploymentHealthPath: ''
  runSecurityScansOnPR: false
  runSecurityScansOnDefaultBranch: true
  customLintDocker: 'Dockerfile.pylint'
  blackDuckDocker: 'Dockerfile.blackduck'
  sapCheckPPMSCompliance: false
  isPPMSUpdateForDockerImage: false
  versionScheme: 'PEP-440'
  githubHttpsUrl: 'https://github.wdf.sap.corp/AI/ai-core-sdk.git'
general:
  buildTool: pip
  scanType: pip
  xMakeBuildQuality: Release
  gitSshKeyCredentialsId: 'SSH_github'
  xMakeDevCredentialsId: 'aif-xmake'
  pythonSourceFolderPath: 'ai_core_sdk/'
  sapPiperDownloadCredentialsId: 'd9e23346-ab04-4c23-add9-409af338fdab'
steps:
  executeBuild:
    xMakeDownloadBuildResult: false
  artifactPrepareVersion:
    buildTool: custom
    filePath: cfg/VERSION
  executeSonarScan:
    instance: 'SAP_EE_sonar'
    tokenVaultPath: 'product/AI/aif_inject_secrets/ai-core-sdk/sonar'
  checkmarxOneExecuteScan:
    checkmarxOneCredentialsId: 'AILIB_CICD_CxOne'
    serverUrl: 'https://checkmarx.tools.sap'
    projectName: 'ai-core-sdk' 
    applicationName: 'AI_LIBRARIES_AND_SDKS'
    preset: 'SAP_Default_Python'    
    filterPattern: '!**/.xmake/**, !**/*.html, !**/*.xml, **/*.py, !**/scripts/**, !**/tests/**, !**/integration_tests/**, !**/component_tests/**, !**/ml-api-facade-performancetest/**, !**/env/**, !**/**vaultSecretContent_*.json, !**/.tox/**'
    generatePdfReport: true
    incremental: true
    fullScansScheduled: false
    fullScanCycle: 10
    avoidDuplicateProjectScans: false
    vulnerabilityThresholdEnabled: true
    vulnerabilityThresholdResult: 'FAILURE'
    vulnerabilityThresholdHigh: 0
    vulnerabilityThresholdMedium: 0
    vulnerabilityThresholdLow: 100
    vulnerabilityThresholdUnit: absolute
  detectExecuteScan:
    serverUrl: 'https://sap.blackducksoftware.com'
    detectTokenCredentialsId: 'AIF_BlackDuckToken'
    customTlsCertificateLinks:
      - http://aia.pki.co.sap.com/aia/SAPNetCA_G2.crt
      - http://aia.pki.co.sap.com/aia/SAP%20Global%20Root%20CA.crt
    projectName: 'ai-core-sdk' # set according to your own requirement
    githubApiUrl: 'https://github.wdf.sap.corp/api/v3/repos/AI/ai-core-sdk'
    githubTokenCredentialsId: 'blackduckpr'
    useDetect9: true
    verbose: true
    versioningModel: 'major'
    groups: 
      - "SAP AI CORE SDK 1.0"
    scanProperties:
      - --detect.python.python3=true
      - --blackduck.signature.scanner.memory=4096
      - --detect.timeout=6000
      - --blackduck.trust.cert=true
      - --logging.level.com.synopsys.integration=DEBUG
      - --detect.maven.excluded.scopes=test
      - --detect.pip.requirements.path=requirements.txt
      - --detect.excluded.directories=.scannerwork/
      - --detect.diagnostic=true # to create diagnostic zip containing files needed for troubleshooting
      #- -- detect.output.path='blackduck/logs' # log files will be generated under this folder
      # - --detect.excluded.detector.types=GIT
      # - --detect.tools.excluded=SIGNATURE_SCAN # to ignore signature scans
      # --detect.cleanup=false # If true(default), the log/zip files created by Detect will be cleaned up automatically.
      # - --detect.blackduck.scan.mode=INTELLIGENT # When scan comes from a PR instead of a branch scan then it usually defaults to RAPID mode. Results for such scan will be not uploaded to the server. Hence added this
  detectExecuteCTPScan: 
    ctp_serverUrl: 'https://sap-cci.app.blackduck.com'
    ctp_detectTokenCredentialsId: 'AIF_BlackDuckToken_CTP'
    ctp_projectName: 'ai-core-sdk' # set according to your own requirement
    ctp_groups: 
      - 'SAP AI CORE SDK 1.0'
    ctp_scanProperties:
      - --detect.python.python3=true
      - --blackduck.signature.scanner.memory=4096
      - --detect.timeout=6000
      - --blackduck.trust.cert=true
      - --logging.level.com.synopsys.integration=DEBUG
      - --detect.maven.excluded.scopes=test
      - --detect.pip.requirements.path=requirements.txt
      - --detect.excluded.directories=.scannerwork/
      - --detect.blackduck.signature.scanner.individual.file.matching=ALL #must for blackduck-CTP scan
  sendNotificationMail:
    notificationRecipients: ''
  slackSendNotification: #Put your team channel name under SAP Machine Learning workspace (sap-ml.slack.com)
    channel: ''
  sapCumulusUpload:
    cumulusFileCredentialsId: 'ai-core-sdk-cumulus'
    pipelineId: 'e4351c5f-1576-4db6-a410-ad4d0efe0b6d'

ContinuousDelivery:
  SetPrOwners: true
  GitHubApiUrl: https://github.wdf.sap.corp/api/v3/repos/AI/ai-core-sdk
  GitHubCredentialsId: 'd9e23346-ab04-4c23-add9-409af338fdab'
  PullRequestRules:
    - targetRepoURI: https://github.tools.sap/MLF/mlf-gitops.git
      credentialId: aif_gitops_user
      runOnBranch: master
      targetBranch: main
      command: scripts/gitops_pr_update_files.sh
      commitFiles:
        - services/ai-core-sdk/source/
    - targetRepoURI: https://github.tools.sap/MLF/mlf-gitops.git
      credentialId: aif_gitops_user
      runOnBranch: \d+\.\d+\.x
      targetBranch: integration
      command: scripts/gitops_pr_update_files.sh
      commitFiles:
        - services/ai-core-sdk/source/

InjectSecretInTestFromVault:
  ComponentTestSecretVaultPath: 'product/AI/aif_inject_secrets/ai-core-sdk/integration_test_secrets/internalprod'
  AcceptanceTestSecretVaultPath: 'product/AI/aif_inject_secrets/ai-core-sdk/integration_test_secrets/internalprod'
  
