apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ai-core-sdk-test-executable
  annotations:
    scenarios.ai.sap.com/description: "ai core sdk test scenario"
    scenarios.ai.sap.com/name: aicoresdk-test-scenario
    executables.ai.sap.com/name: "aicore-sdk-test"
    executables.ai.sap.com/description: "ai core sdk test executable"
  labels:
    ai.sap.com/version: 0.0.1
    scenarios.ai.sap.com/id: aaaaaaaa-9999-8888-7777-uuuuuuuuuuuu
spec:
  entrypoint: ai-core-sdk
  imagePullSecrets:
    - name: gcp-artifact-registry
    - name: sap-dmz-docker-registry
    - name: tests-docker-image-secret
  templates:
  - name: ai-core-sdk
    steps:
    - - name: ai-core-sdk-template
        template: ai-core-sdk-template

  - name: ai-core-sdk-template
    container:
      image: {{ printf "%s/%s:%s" $.Values.imageRepository $.Values.image $.Chart.Version }}
      command:
        - python3
        - '-c'
      args:
       - |
        from ai_core_sdk.tracking import Tracking
        from ai_core_sdk.exception import AICoreSDKException
        from ai_core_sdk.exception import AIAPINotFoundException

        import os
        import string
        import random
        from datetime import datetime
        from hamcrest import assert_that, equal_to, has_length, matches_regexp, is_in, not_, contains_string, has_key

        #initialising core sdk client with AI API url, auth url, client id and client secret and resource group
        # Please replace base_url, auth_url, client_id, client_secret and resource_group as needed.


        def random_string(length=10):
            letters = string.ascii_lowercase
            result_str = ''.join(random.choice(letters) for i in range(length))
            return result_str


        def get_datetime():
            datetimeObj = datetime.now()
            return datetimeObj.strftime("%Y-%m-%dT%H:%M:%S.%fZ")


        def random_metrics():
            return [
                {
                    "name": random_string(),
                    "value": random.random(),
                    "timestamp": get_datetime(),
                    "step": random.randint(0, 10),
                    "labels": [
                        {
                            "name": "group",
                            "value": random_string()
                        }
                    ]
                }
            ]

        def random_tags():
            return [{
                'name': random_string(),
                'value': random_string()
            }]

        def random_customInfo():
            return [{
                'name': random_string(),
                'value': "[{'Predicted': 'False','Actual': 'True'}]"
            }]

        tracking_client = Tracking()

        from ai_api_client_sdk.models.metric import Metric
        from ai_api_client_sdk.models.metric_custom_info import MetricCustomInfo
        from ai_api_client_sdk.models.metric_tag import MetricTag

        # Log Metrics, Tags, CustomInfo to a single executionId

        metrics_patch_data = random_metrics()

        execution_id = os.getenv("AICORE_EXECUTION_ID")


        #framing the arguments for modify function call
        body = {'execution_id': execution_id,
                        'tags': [MetricTag.from_dict(mtd) for mtd in random_tags()],
                        'metrics': [Metric.from_dict(md) for md in random_metrics()],
                        'custom_info': [MetricCustomInfo.from_dict(mcid) for mcid in random_customInfo()]
        }

        #calling modify function
        tracking_client.modify(**body)

        response = tracking_client.query(execution_ids=[execution_id])

        resource = response.resources[0]
        assert_that(resource.metrics, has_length(1))
        assert_that(resource.metrics[0].name, matches_regexp('[\\w]+'))
        assert_that(str(resource.metrics[0].value), matches_regexp('(\d+(\.\d*)?|\.\d+)'))
        assert_that(resource.tags, has_length(1))
        assert_that(resource.tags[0].name, matches_regexp('[\\w]+'))
        assert_that(resource.tags[0].value, matches_regexp('[\\w]+'))
        assert_that(resource.custom_info, has_length(1))

        tracking_client.delete(execution_id=execution_id)
        print("Metric Resources associated with the execution are deleted")

        tracking_client.log_metrics([Metric.from_dict(md) for md in random_metrics()])

        response = tracking_client.query(execution_ids=[execution_id])
        resource = response.resources[0]
        assert_that(resource.metrics, has_length(1))
        assert_that(resource.metrics[0].name, matches_regexp('[\\w]+'))
        assert_that(str(resource.metrics[0].value), matches_regexp('(\d+(\.\d*)?|\.\d+)'))

        tracking_client.set_tags([MetricTag.from_dict(mtd) for mtd in random_tags()])
        response = tracking_client.query(execution_ids=[execution_id])
        resource = response.resources[0]
        assert_that(resource.tags, has_length(1))
        assert_that(resource.tags[0].name, matches_regexp('[\\w]+'))
        assert_that(resource.tags[0].value, matches_regexp('[\\w]+'))

        tracking_client.set_custom_info([MetricCustomInfo.from_dict(mcid) for mcid in random_customInfo()])
        response = tracking_client.query(execution_ids=[execution_id])
        resource = response.resources[0]
        assert_that(resource.custom_info, has_length(1))

        tracking_client.delete(execution_id=execution_id)
        print("Metric Resources associated with the execution are deleted")

        try:
            tracking_client.delete(execution_id=execution_id)
        except AIAPINotFoundException as error:
            assert_that(str(error), contains_string('Failed to delete /metrics'))
            assert_that(str(error), contains_string("Can't find metric resource associated with execution id"))

        print("Finished test cases")
