name: publish-testpypi

on:
  release:
    types: [published]

jobs:
  publish-pypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get package from tag
        id: meta
        run: |
          TAG="${{ github.event.release.tag_name }}"
          PACKAGE="${TAG%%-v*}"
          echo "package=${PACKAGE}" >> "$GITHUB_OUTPUT"

      - name: Setup
        uses: ./.github/actions/setup
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Build package
        run: |
          uv build --package sap-ai-sdk-${{ steps.meta.outputs.package }} --out-dir packages/${{ steps.meta.outputs.package }}/dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: false
          packages-dir: packages/${{ steps.meta.outputs.package }}/dist/
