name: snapshot-release

on:
  push:
    branches:
      - main
      - os-migration

jobs:
  snapshot-release:
    runs-on: ubuntu-latest
    steps:
      - uses: SAP/ai-sdk-python/.github/actions/setup@os-migration
        with:
          fetch-depth: 0
          registry-username: ${{ secrets.ARTIFACTORY_USERNAME }}
          registry-token: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Bump base version
        id: bump-base
        working-directory: packages/base
        run: |
          uv run cz bump --version-files-only --prerelease alpha
          sed -i "s/a0$/a$(date +%s)/" pyproject.toml
          echo "version=$(uv run cz version --project)" >> "$GITHUB_OUTPUT"
          # pin core dependency
          sed -i "s/sap-ai-sdk-base~=[^ ,]*/sap-ai-sdk-base==$(uv run cz version --project)/" ../core/pyproject.toml

      - name: Bump core version
        id: bump-core
        working-directory: packages/core
        run: |
          uv run cz bump --version-files-only --prerelease alpha
          sed -i "s/a0$/a$(date +%s)/" pyproject.toml
          echo "version=$(uv run cz version --project)" >> "$GITHUB_OUTPUT"
          # pin gen dependency
          sed -i "s/sap-ai-sdk-core>=[^ ,]*/sap-ai-sdk-core==$(uv run cz version --project)/" ../gen/pyproject.toml

      - name: Bump gen version
        working-directory: packages/gen
        run: |
          uv run cz bump --version-files-only --prerelease alpha
          sed -i "s/a0$/a$(date +%s)/" pyproject.toml

      - name: Build base
        run: uv build --package sap-ai-sdk-base --out-dir packages/base/dist

      - name: Build core
        run: uv build --package sap-ai-sdk-core --out-dir packages/core/dist

      - name: Build gen
        run: uv build --package sap-ai-sdk-gen --out-dir packages/gen/dist

      # - name: Release base to Artifactory #(TODO: currently not working)
      #   working-directory: packages/base
      #   run: |
      #     uv publish \
      #       --index-url https://common.repositories.cloud.sap/artifactory/api/pypi/build.snapshots.pypi/legacy/ \
      #       --username ${{ secrets.ARTIFACTORY_USERNAME }} \ # TODO: use separate credentials for internal artifactory
      #       --password ${{ secrets.ARTIFACTORY_TOKEN }} \ # TODO: use separate credentials for internal artifactory
      #       dist/

      # - name: Release core to Artifactory #(TODO: currently not working)
      #   working-directory: packages/core
      #   run: |
      #     uv publish \
      #       --index-url https://common.repositories.cloud.sap/artifactory/api/pypi/build.snapshots.pypi/legacy/ \
      #       --username ${{ secrets.ARTIFACTORY_USERNAME }} \ # TODO: use separate credentials for internal artifactory
      #       --password ${{ secrets.ARTIFACTORY_TOKEN }} \ # TODO: use separate credentials for internal artifactory
      #       dist/

      # - name: Release gen to Artifactory #(TODO: currently not working)
      #   working-directory: packages/gen
      #   run: |
      #     uv publish \
      #       --index-url https://common.repositories.cloud.sap/artifactory/api/pypi/build.snapshots.pypi/legacy/ \
      #       --username ${{ secrets.ARTIFACTORY_USERNAME }} \ # TODO: use separate credentials for internal artifactory
      #       --password ${{ secrets.ARTIFACTORY_TOKEN }} \ # TODO: use separate credentials for internal artifactory
      #       dist/
