name: teardown-integration-env

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - uses: SAP/ai-sdk-python/.github/actions/setup@7c4e0ae0f4c548da7a8fd5a630ba849ec38296c6 # main

      - name: Tear down integration test environment
        run: bash scripts/teardown-integration-env.sh
