name: zizmor

on:
  pull_request:
    paths:
      - '.github/**'
  push:
    branches:
      - 'main'
    paths:
      - '.github/**'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install zizmor
        run: pip install zizmor

      - name: Run zizmor (log)
        run: zizmor --config zizmor.yml --min-severity high .github/

      - name: Run zizmor (SARIF)
        uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
        if: always()
        with:
          config: zizmor.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
