from dataclasses import dataclass
from typing import List, Optional, Dict, Any, Union

from gen_ai_hub.orchestration.models.message import Message, FunctionCall
from gen_ai_hub.orchestration.models.multimodal_items import ContentPart


@dataclass
class ToolCallChunk:
    """Represents a chunk of a tool call in a streaming chat response."""
    index: int
    """The index of this tool call chunk in the sequence of chunks."""
    id: Optional[str] = None
    """The unique identifier for the tool call."""
    type: Optional[str] = None
    """The type of tool call, e.g., 'function' ."""
    function: Optional[FunctionCall] = None
    """The function call details associated with this tool call chunk."""


@dataclass
class ChatDelta:
    """Represents a partial update in a streaming chat response."""
    content: Union[str, List[ContentPart]]
    """The text content of the chat delta."""
    role: Optional[str] = None
    """Optional role identifier (e.g., 'assistant', 'user') for the message delta."""
    refusal: Optional[str] = None
    """Optional refusal reason if the model refused to generate content."""
    tool_calls: Optional[List[ToolCallChunk]] = None
    """Optional list of tool call chunks associated with this chat delta."""


@dataclass
class LLMUsage:
    """Represents the token usage statistics for an LLM (Large Language Model) operation.
    """
    completion_tokens: int
    """The number of tokens generated by the model in the response."""
    prompt_tokens: int
    """The number of tokens in the input prompt."""
    total_tokens: int
    """The total number of tokens used, including both prompt and completion tokens."""


@dataclass
class LLMChoice:
    """
    Represents an individual choice or response generated by the LLM.
    
    Attributes:
        index: The index of this particular choice in the list of possible choices.

        message: The message object containing the role and content of the response.

        finish_reason: The reason why the model stopped generating tokens.

        logprobs: Optional dictionary containing token log probabilities.
    """
    index: int
    """The index of this particular choice in the list of possible choices."""
    message: Message
    """The message object containing the role and content of the response."""
    finish_reason: str
    """The reason why the model stopped generating tokens."""
    logprobs: Optional[Dict[str, float]] = None
    """Optional dictionary containing token log probabilities."""


@dataclass
class LLMChoiceStreaming:
    """
        Represents a streaming choice or partial response generated by the LLM.

        Attributes:
            index: The index of this particular choice in the list of possible choices.

            delta: The partial update (ChatDelta) for this choice.

            finish_reason: Optional reason for why the generation stopped, may be None during streaming.

            logprobs: Optional dictionary containing token log probabilities.
    """
    index: int
    """The index of this particular choice in the list of possible choices."""
    delta: ChatDelta
    """The partial update (ChatDelta) for this choice."""
    finish_reason: Optional[str] = None
    """Optional reason for why the generation stopped, may be None during streaming."""
    logprobs: Optional[Dict[str, float]] = None
    """Optional dictionary containing token log probabilities."""


@dataclass
class BaseLLMResult:
    """
    Base class for LLM results containing common attributes.

    Attributes:
        id: Unique identifier for the LLM operation.
        object: Type of object returned (e.g., "chat.completion").
        created: Timestamp when this result was created.
        model: Name or identifier of the model used.
    """
    id: str
    object: str
    created: int
    model: str


@dataclass
class LLMResult(BaseLLMResult):
    """
    Represents the complete result from an LLM operation.

    Attributes:
        id: The unique identifier for this LLM operation.

        object: The type of object returned (typically "chat.completion").

        created: The timestamp when this result was created.

        model: The name or identifier of the model used for generating the result.

        choices: A list of possible choices generated by the LLM.

        usage: The token usage statistics for this operation.

        system_fingerprint: An optional system fingerprint for tracking the model used.
    """
    choices: List[LLMChoice]
    """A list of possible choices generated by the LLM."""
    usage: LLMUsage
    """The token usage statistics for this operation."""
    system_fingerprint: Optional[str] = None
    """An optional system fingerprint for tracking the model used."""


@dataclass
class LLMResultStreaming(BaseLLMResult):
    """
        Represents a streaming result from an LLM operation.

        Attributes:
            id: The unique identifier for this LLM operation.

            object: The type of object returned (typically "chat.completion.chunk").

            created: The timestamp when this result was created.

            model: The name or identifier of the model used.

            choices: A list of streaming choices generated by the LLM.

            usage: optional token usage statistics for this operation.

            system_fingerprint: An optional system fingerprint for tracking the model used.
    """
    choices: List[LLMChoiceStreaming]
    """A list of streaming choices generated by the LLM."""
    usage: Optional[LLMUsage] = None
    """optional token usage statistics for this operation."""
    system_fingerprint: Optional[str] = None
    """An optional system fingerprint for tracking the model used."""


@dataclass
class GenericModuleResult:
    """Represents a generic module result in the orchestration process."""

    message: str
    """A message or description generated by the module."""
    data: Optional[Dict[str, Any]] = None
    """Additional data relevant to the module result."""


@dataclass
class BaseModuleResults:
    """
        Base class for module results containing grounding, common filtering and masking attributes.

        Attributes:
            input_filtering: Results from the input filtering module.

            output_filtering: Results from the output filtering module.

            input_masking: Results from the input masking module.

            grounding: A list of extracted text to be provided as grounding context.

            input_translation: Results from the input translation module.

            output_translation: Results from the output translation module.
    """
    input_filtering: Optional[GenericModuleResult] = None
    """Results from the input filtering module."""
    output_filtering: Optional[GenericModuleResult] = None
    """Results from the output filtering module."""
    input_masking: Optional[GenericModuleResult] = None
    """Results from the input masking module."""
    grounding: Optional[GenericModuleResult] = None
    """A list of extracted text to be provided as grounding context."""
    input_translation: Optional[GenericModuleResult] = None
    """Results from the input translation module."""
    output_translation: Optional[GenericModuleResult] = None
    """Results from the output translation module."""


@dataclass
class ModuleResults(BaseModuleResults):
    """
    Represents the results of various modules used in processing an orchestration request.

    Attributes:
        templating: A list of messages that define the conversation's context or template.

        llm: The result from the LLM operation.

        input_filtering: The result of any input filtering, if applicable.

        output_filtering: The result of any output filtering, if applicable.

        input_masking: The result of input masking, if applicable.

        output_unmasking: The result of output unmasking, if applicable.
    """
    llm: Optional[LLMResult] = None
    """The result from the LLM operation."""
    templating: Optional[List[Message]] = None
    """A list of messages that define the conversation's context or template."""
    output_unmasking: Optional[List[LLMChoice]] = None
    """The result of output unmasking, if applicable."""


@dataclass
class ModuleResultsStreaming(BaseModuleResults):
    """
        Represents the streaming results of various modules used in processing an orchestration request.

        Attributes:
            llm: The streaming result from the LLM operation.

            templating: A list of chat deltas that define the conversation's context or template.

            input_filtering: The result of any input filtering, if applicable.

            output_filtering: The result of any output filtering, if applicable.

            input_masking: The result of input masking, if applicable.

            output_unmasking: The result of output unmasking for streaming responses.
    """
    llm: Optional[LLMResultStreaming] = None
    """The streaming result from the LLM operation."""
    templating: Optional[List[ChatDelta]] = None
    """A list of chat deltas that define the conversation's context or template."""
    output_unmasking: Optional[List[LLMChoiceStreaming]] = None
    """The result of output unmasking for streaming responses."""


@dataclass
class OrchestrationResponse:
    """
    Represents the complete response from an orchestration process.

    Attributes:
        request_id: The unique identifier for the request being processed.

        module_results: The results from the various modules involved in processing the request.

        orchestration_result: The final result from the orchestration, typically mirroring the LLM result.
    """
    request_id: str
    """The unique identifier for the request being processed."""
    module_results: ModuleResults
    """The results from the various modules involved in processing the request."""
    orchestration_result: LLMResult
    """The final result from the orchestration, typically mirroring the LLM result."""

    @property
    def content(self) -> str:
        """Gets the content of the first choice in the orchestration result.

        :raises ValueError: If there are no choices available in the orchestration result.
        :return: The content of the first choice.
        :rtype: str
        """

        if not self.orchestration_result.choices:
            raise ValueError("No choices available in the orchestration result.")

        return self.orchestration_result.choices[0].message.content

@dataclass
class OrchestrationResponseStreaming:
    """
        Represents the streaming response from an orchestration process.

        Attributes:
            request_id: The unique identifier for the request being processed.

            module_results: The streaming results from the various modules involved in processing the request.

            orchestration_result: The streaming result from the orchestration.
    """
    request_id: str
    """The unique identifier for the request being processed."""
    module_results: ModuleResultsStreaming
    """The streaming results from the various modules involved in processing the request."""
    orchestration_result: LLMResultStreaming
    """The streaming result from the orchestration."""

@dataclass
class OrchestrationResponseWithRetries(OrchestrationResponse):
    """
    Extended OrchestrationResponse that includes retry count information.
    
    This is returned when using retry-enabled methods like run_with_retries().
    
    Attributes:
        retries: Number of retry attempts that were made to successfully complete this request.
    """
    retries: int = 0
    """Number of retry attempts that were made to successfully complete this request."""
