apiVersion: v1
kind: Secret
metadata:
  name: gcp-artifact-registry
  annotations:
    replicator.v1.mittwald.de/replicate-from: cluster-secrets/gcp-artifact-registry
    replicator.v1.mittwald.de/replicated-at: ''
    replicator.v1.mittwald.de/replicated-from-version: ''
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
